spring.application.name=backend

server.port=4722

spring.datasource.url=jdbc:postgresql://localhost:5432/digital_journal_app
spring.datasource.password=Postgre@4722
spring.datasource.username=postgres

spring.app.jwtSecret=hsdfbcweufbyhqkbhnrfejhnf7815y7814678947839247895623
spring.app.jwtCookie=SpringDJ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
